In [1]:
import numpy as np

from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression

from SimpleLinearRegression import SimpleLinearRegression as SLR
from MultipleLinearRegression import MultipleLinearRegression as MLR
from LogisticRegression import LogisticRegression as myLogisticRegression

from scoring import RSS, log_loss

from sklearn.datasets import load_boston
from sklearn.datasets import load_breast_cancer

In [2]:
boston = load_boston()
X = boston.data
y = boston.target

In [3]:
x = X[:,1]

In [4]:
LR = LinearRegression()
LR.fit(x.reshape(-1, 1), y)
y_hat = LR.predict(x.reshape(-1,1))

In [5]:
print(LR.coef_)
print(LR.intercept_)

[0.14213999]
20.917579117799832


In [6]:
mySLR = SLR()
mySLR.fit(x, y)
my_hat = mySLR.predict(x)

In [7]:
mySLR.model

{'b0': 20.917579117799832, 'b1': 0.14213999415535436}

In [8]:
print(RSS(y, my_hat))
print(RSS(y, y_hat))

37166.55822394633
37166.55822394634


In [9]:
LR = LinearRegression()
LR.fit(X, y)
y_hat = LR.predict(X)

In [10]:
print(LR.coef_)
print(LR.intercept_)

[-1.07170557e-01  4.63952195e-02  2.08602395e-02  2.68856140e+00
 -1.77957587e+01  3.80475246e+00  7.51061703e-04 -1.47575880e+00
  3.05655038e-01 -1.23293463e-02 -9.53463555e-01  9.39251272e-03
 -5.25466633e-01]
36.49110328036191


In [11]:
myMLR = MLR()
myMLR.fit(X, y)
my_hat = myMLR.predict(X)

In [12]:
myMLR.betas

array([ 3.64911033e+01, -1.07170557e-01,  4.63952195e-02,  2.08602395e-02,
        2.68856140e+00, -1.77957587e+01,  3.80475246e+00,  7.51061703e-04,
       -1.47575880e+00,  3.05655038e-01, -1.23293463e-02, -9.53463555e-01,
        9.39251272e-03, -5.25466633e-01])

In [2]:
breast = load_breast_cancer()
X = breast.data
y = breast.target

In [3]:
LR = LogisticRegression(C=100000000000)
LR.fit(X, y)
y_hat = LR.predict_proba(X)

In [15]:
myLR = myLogisticRegression()
myLR.fit(X, y)
my_hat = myLR.predict(X, prob=True)

/home/nick/Projects/machine_learning_from_scratch/src/LogisticRegression.py:157: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-X.dot(betas)))


In [16]:
print(log_loss(y, y_hat[:,1]))
print(log_loss(y, my_hat))

0.05589948995600698
21.670198898037278


In [17]:
y.shape[0]

569

In [18]:
len(y)

569

In [19]:
np.log(y)

/home/nick/Envs/py36mlfs_testing/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf,
       -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf,   0.,   0.,   0.,
       -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf,
       -inf, -inf, -inf, -inf,   0., -inf, -inf, -inf, -inf, -inf, -inf,
       -inf, -inf,   0., -inf,   0.,   0.,   0.,   0.,   0., -inf, -inf,
         0., -inf, -inf,   0.,   0.,   0.,   0., -inf,   0., -inf, -inf,
         0.,   0.,   0.,   0., -inf,   0., -inf, -inf,   0., -inf,   0.,
       -inf, -inf,   0.,   0.,   0., -inf, -inf,   0., -inf, -inf, -inf,
         0.,   0.,   0., -inf,   0.,   0., -inf, -inf,   0.,   0.,   0.,
       -inf, -inf,   0.,   0.,   0.,   0., -inf,   0.,   0., -inf,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0., -inf, -inf, -inf,   0.,
       -inf, -inf,   0.,   0.,   0., -inf, -inf,   0., -inf,   0., -inf,
       -inf,   0., -inf, -inf,   0.,   0., -inf,   0.,   0., -inf,   0.,
         0.,   0.,   0., -inf,   0.,   0.,   0.,   

In [17]:
my_hat

array([1.e-15, 1.e-15, 1.e-15, 1.e-15, 1.e-15, 1.e-15, 1.e-15, 1.e-15,
       1.e-15, 1.e-15, 1.e-15, 1.e-15, 1.e-15, 1.e-15, 1.e-15, 1.e-15,
       1.e-15, 1.e-15, 1.e-15, 1.e-15, 1.e-15, 1.e-15, 1.e-15, 1.e-15,
       1.e-15, 1.e-15, 1.e-15, 1.e-15, 1.e-15, 1.e-15, 1.e-15, 1.e-15,
       1.e-15, 1.e-15, 1.e-15, 1.e-15, 1.e-15, 1.e-15, 1.e-15, 1.e-15,
       1.e-15, 1.e-15, 1.e-15, 1.e-15, 1.e-15, 1.e-15, 1.e-15, 1.e-15,
       1.e-15, 1.e-15, 1.e-15, 1.e-15, 1.e-15, 1.e-15, 1.e-15, 1.e-15,
       1.e-15, 1.e-15, 1.e-15, 1.e-15, 1.e-15, 1.e-15, 1.e-15, 1.e-15,
       1.e-15, 1.e-15, 1.e-15, 1.e-15, 1.e-15, 1.e-15, 1.e-15, 1.e-15,
       1.e-15, 1.e-15, 1.e-15, 1.e-15, 1.e-15, 1.e-15, 1.e-15, 1.e-15,
       1.e-15, 1.e-15, 1.e-15, 1.e-15, 1.e-15, 1.e-15, 1.e-15, 1.e-15,
       1.e-15, 1.e-15, 1.e-15, 1.e-15, 1.e-15, 1.e-15, 1.e-15, 1.e-15,
       1.e-15, 1.e-15, 1.e-15, 1.e-15, 1.e-15, 1.e-15, 1.e-15, 1.e-15,
       1.e-15, 1.e-15, 1.e-15, 1.e-15, 1.e-15, 1.e-15, 1.e-15, 1.e-15,
      

In [9]:
y_hat

array([[1.00000000e+00, 3.05902321e-07],
       [9.99999999e-01, 3.05902321e-07],
       [1.00000000e+00, 3.05902321e-07],
       ...,
       [9.99639559e-01, 3.60440932e-04],
       [1.00000000e+00, 3.05902321e-07],
       [1.60064693e-03, 9.98399353e-01]])